logging:
  level:
    root: INFO

com:
  gotz9:
    security:
      web:
        permitted-uri:
          - "/index"

spring:
  datasource:
    url: jdbc:mysql://localhost/security?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1111
